const QUESTION_BANK = {
  categories: [
    { id: 'basics', name: '基礎語法', icon: '📝', color: '#4CAF50' },
    { id: 'datatypes', name: '資料型別', icon: '🔢', color: '#2196F3' },
    { id: 'operators', name: '運算子', icon: '⚙️', color: '#FF9800' },
    { id: 'control', name: '控制流程', icon: '🔀', color: '#9C27B0' },
    { id: 'functions', name: '函式', icon: '🔧', color: '#F44336' },
    { id: 'arrays', name: '陣列', icon: '📦', color: '#00BCD4' },
    { id: 'pointers', name: '指標', icon: '👉', color: '#795548' },
    { id: 'strings', name: '字串', icon: '💬', color: '#607D8B' },
    { id: 'structs', name: '結構體', icon: '🏗️', color: '#E91E63' },
    { id: 'memory', name: '記憶體管理', icon: '🧠', color: '#FF5722' },
  ],

  questions: {
    basics: [
      {
        id: 'b1',
        type: 'multiple',
        difficulty: 'easy',
        question: 'C 語言程式的進入點（入口函式）是哪一個？',
        code: null,
        options: ['start()', 'main()', 'begin()', 'init()'],
        answer: 1,
        explanation: 'C 語言規定程式必須有一個 `main()` 函式作為程式的起始點。作業系統在執行程式時，會從 main() 開始執行。',
      },
      {
        id: 'b2',
        type: 'multiple',
        difficulty: 'easy',
        question: '下列哪個標頭檔（header file）提供 `printf()` 函式？',
        code: null,
        options: ['<stdlib.h>', '<string.h>', '<stdio.h>', '<math.h>'],
        answer: 2,
        explanation: '`<stdio.h>` 是標準輸入/輸出標頭檔（Standard Input/Output），其中定義了 printf()、scanf()、fopen() 等函式。',
      },
      {
        id: 'b3',
        type: 'multiple',
        difficulty: 'easy',
        question: 'C 語言中，單行注解使用哪種語法？',
        code: null,
        options: ['# 這是注解', '// 這是注解', '-- 這是注解', '/* 這是注解'],
        answer: 1,
        explanation: '`//` 用於單行注解（C99 標準引入）。`/* */` 用於多行注解。`#` 是前置處理器指令（如 #include）。',
      },
      {
        id: 'b4',
        type: 'multiple',
        difficulty: 'medium',
        question: '以下程式碼的輸出是什麼？',
        code: '#include <stdio.h>\nint main() {\n    printf("Hello");\n    printf(" World");\n    return 0;\n}',
        options: ['Hello\nWorld', 'Hello World', 'HelloWorld', '編譯錯誤'],
        answer: 1,
        explanation: 'printf() 不會自動換行。"Hello" 和 " World" 會連續輸出，結果為 "Hello World"。若需換行，需加上 \\n 跳脫字元。',
      },
      {
        id: 'b5',
        type: 'fill',
        difficulty: 'easy',
        question: '在 C 語言中，每個敘述（statement）的結尾必須加上 _____ 符號。',
        code: null,
        answer: ';',
        hint: '這個符號也叫做分號',
        explanation: '每個 C 語言敘述結尾必須有分號 `;`，這告訴編譯器一個敘述在此結束。忘記加分號是初學者最常見的錯誤之一。',
      },
      {
        id: 'b6',
        type: 'multiple',
        difficulty: 'medium',
        question: '`return 0;` 在 main() 函式中代表什麼？',
        code: null,
        options: [
          '程式跳回第一行重新執行',
          '程式正常結束，回傳 0 給作業系統',
          '程式遇到錯誤停止',
          '程式進入無限迴圈',
        ],
        answer: 1,
        explanation: 'main() 回傳 0 代表程式正常結束（exit code 0）。非零值通常代表錯誤。作業系統或呼叫程式可以讀取此回傳值來判斷執行結果。',
      },
      {
        id: 'b7',
        type: 'multiple',
        difficulty: 'hard',
        question: '下列哪個不是 C 語言的保留字（keyword）？',
        code: null,
        options: ['auto', 'register', 'string', 'volatile'],
        answer: 2,
        explanation: '`string` 不是 C 語言的保留字（它是 C++ 的 std::string 類別）。在 C 中，字串以 `char` 陣列表示。`auto`、`register`、`volatile` 都是 C 語言保留字。',
      },
      {
        id: 'b8',
        type: 'fill',
        difficulty: 'medium',
        question: '在 C 語言中，前置處理器包含標頭檔的指令是 `_____ <stdio.h>`',
        code: null,
        answer: '#include',
        hint: '以 # 開頭',
        explanation: '`#include` 是前置處理器（preprocessor）指令，在編譯之前將指定標頭檔的內容插入程式碼中。`< >` 用於系統標頭檔，`" "` 用於自訂標頭檔。',
      },
    ],

    datatypes: [
      {
        id: 'd1',
        type: 'multiple',
        difficulty: 'easy',
        question: '`int` 型別在大多數 64 位元系統中占用多少位元組（bytes）？',
        code: null,
        options: ['1 bytes', '2 bytes', '4 bytes', '8 bytes'],
        answer: 2,
        explanation: '在大多數現代系統中，`int` 佔 4 bytes（32 bits），可儲存 -2,147,483,648 到 2,147,483,647 的整數。實際大小依平台而定，由 `sizeof(int)` 確認。',
      },
      {
        id: 'd2',
        type: 'multiple',
        difficulty: 'easy',
        question: '下列哪個資料型別用於儲存單一字元？',
        code: null,
        options: ['string', 'char', 'text', 'letter'],
        answer: 1,
        explanation: '`char` 型別用於儲存單一字元，佔 1 byte。字元以單引號表示，例如 `char c = \'A\';`。',
      },
      {
        id: 'd3',
        type: 'multiple',
        difficulty: 'medium',
        question: '`float` 與 `double` 的主要差異是什麼？',
        code: null,
        options: [
          'float 只能存整數，double 可以存小數',
          'float 佔 4 bytes，double 佔 8 bytes，精度更高',
          'float 是 C 語言特有，double 是 C++ 特有',
          '兩者完全相同，只是名稱不同',
        ],
        answer: 1,
        explanation: '`float` 佔 4 bytes，約 7 位有效數字；`double` 佔 8 bytes，約 15-16 位有效數字。科學計算通常使用 double 以獲得更高精度。',
      },
      {
        id: 'd4',
        type: 'multiple',
        difficulty: 'medium',
        question: '`unsigned int` 與 `int` 的差異是？',
        code: null,
        options: [
          'unsigned int 只能存偶數',
          'unsigned int 不能存負數，但正數範圍更大',
          'unsigned int 佔用更多記憶體',
          'unsigned int 運算速度更慢',
        ],
        answer: 1,
        explanation: '`unsigned int` 不存負數，範圍為 0 到 4,294,967,295（比有號整數多一倍的正數範圍）。適合用於不需要負數的計數器、位元操作等場合。',
      },
      {
        id: 'd5',
        type: 'fill',
        difficulty: 'easy',
        question: '宣告一個名為 `score`、型別為整數的變數，語法為：`_____ score;`',
        code: null,
        answer: 'int',
        hint: '整數型別的關鍵字',
        explanation: '`int score;` 宣告了一個整數型別的變數 score。宣告語法為：型別名稱 + 空格 + 變數名稱 + 分號。',
      },
      {
        id: 'd6',
        type: 'multiple',
        difficulty: 'hard',
        question: '以下程式碼輸出為何？',
        code: '#include <stdio.h>\nint main() {\n    char c = 65;\n    printf("%c\\n", c);\n    return 0;\n}',
        options: ['65', 'A', 'char', '編譯錯誤'],
        answer: 1,
        explanation: '`%c` 格式符將數值以字元輸出。ASCII 碼 65 對應的字元是 `A`。若用 `%d` 則會輸出 65。這展示了 char 本質上是整數。',
      },
      {
        id: 'd7',
        type: 'multiple',
        difficulty: 'hard',
        question: '`sizeof` 運算子的用途是？',
        code: null,
        options: [
          '計算陣列元素數量',
          '回傳型別或變數佔用的位元組數',
          '比較兩個值的大小',
          '取得字串長度',
        ],
        answer: 1,
        explanation: '`sizeof` 在編譯期計算並回傳型別或變數的大小（bytes）。例如 `sizeof(int)` 通常回傳 4。不同於 `strlen()`，`sizeof` 對陣列回傳整個陣列大小。',
      },
    ],

    operators: [
      {
        id: 'o1',
        type: 'multiple',
        difficulty: 'easy',
        question: '在 C 語言中，`=` 和 `==` 的差異是？',
        code: null,
        options: [
          '兩者相同，可以互換使用',
          '`=` 是指派運算子，`==` 是相等比較運算子',
          '`=` 用於浮點數，`==` 用於整數',
          '`==` 不存在於 C 語言',
        ],
        answer: 1,
        explanation: '`=` 是指派（assignment）運算子，將右側值存入左側變數；`==` 是比較運算子，判斷兩值是否相等並回傳 true/false。混用是常見錯誤，例如 `if (x = 5)` 永遠為真。',
      },
      {
        id: 'o2',
        type: 'multiple',
        difficulty: 'easy',
        question: '`%` 運算子在 C 語言中代表什麼？',
        code: null,
        options: ['百分比計算', '取餘數（modulo）', '位元 OR 運算', '浮點數除法'],
        answer: 1,
        explanation: '`%` 是取餘數運算子（modulo）。例如 `7 % 3 = 1`（7 除以 3 餘 1）。常用於判斷奇偶數（`n % 2 == 0` 為偶數）或循環計數。',
      },
      {
        id: 'o3',
        type: 'multiple',
        difficulty: 'medium',
        question: '`i++` 和 `++i` 的差異是？',
        code: null,
        options: [
          '兩者完全相同',
          '`i++` 先使用再加1，`++i` 先加1再使用',
          '`++i` 比 `i++` 快10倍',
          '`i++` 加1，`++i` 加2',
        ],
        answer: 1,
        explanation: '`i++`（後置遞增）先回傳 i 的值，再將 i 加 1；`++i`（前置遞增）先將 i 加 1，再回傳新值。例如：若 i=5，`x = i++` 後 x=5, i=6；`x = ++i` 後 x=6, i=6。',
      },
      {
        id: 'o4',
        type: 'multiple',
        difficulty: 'medium',
        question: '以下程式碼輸出為何？',
        code: '#include <stdio.h>\nint main() {\n    int a = 10, b = 3;\n    printf("%d\\n", a / b);\n    return 0;\n}',
        options: ['3.33', '3', '4', '3.0'],
        answer: 1,
        explanation: '兩個整數相除（整數除法）結果仍為整數，小數部分直接捨去（不是四捨五入）。10 / 3 = 3（餘 1）。若需小數結果，需將其中一個轉為浮點數：`(float)a / b`。',
      },
      {
        id: 'o5',
        type: 'multiple',
        difficulty: 'hard',
        question: '以下條件的結果為何？`(5 > 3) && (2 > 8)`',
        code: null,
        options: ['1（true）', '0（false）', '5', '編譯錯誤'],
        answer: 1,
        explanation: '`&&` 是邏輯 AND 運算子，兩個條件都必須為真結果才為真。`5 > 3` 為真（1），`2 > 8` 為假（0）。1 && 0 = 0（false）。',
      },
      {
        id: 'o6',
        type: 'fill',
        difficulty: 'medium',
        question: '在 C 語言中，邏輯 OR 運算子的符號是 _____',
        code: null,
        answer: '||',
        hint: '兩個相同符號',
        explanation: '`||` 是邏輯 OR 運算子，只要其中一個條件為真，結果就為真。例如 `(a > 0) || (b > 0)` 表示 a 或 b 至少一個大於 0。',
      },
      {
        id: 'o7',
        type: 'multiple',
        difficulty: 'hard',
        question: '三元運算子 `condition ? a : b` 的意思是？',
        code: null,
        options: [
          '計算 condition、a、b 的平均值',
          '若 condition 為真則結果為 a，否則為 b',
          '宣告三個變數',
          '只有 C++ 才有此語法',
        ],
        answer: 1,
        explanation: '三元運算子（ternary operator）是 if-else 的簡短寫法。`int max = (a > b) ? a : b;` 等同於：若 a > b 則 max = a，否則 max = b。常用於簡短的條件賦值。',
      },
    ],

    control: [
      {
        id: 'c1',
        type: 'multiple',
        difficulty: 'easy',
        question: '`for (int i = 0; i < 5; i++)` 迴圈總共執行幾次？',
        code: null,
        options: ['4 次', '5 次', '6 次', '無限次'],
        answer: 1,
        explanation: 'i 從 0 開始，條件 `i < 5` 在 i = 0, 1, 2, 3, 4 時為真（共 5 次），i = 5 時條件不成立，迴圈結束。',
      },
      {
        id: 'c2',
        type: 'multiple',
        difficulty: 'easy',
        question: '`while` 與 `do-while` 的最主要差異是？',
        code: null,
        options: [
          '兩者完全相同',
          'do-while 保證至少執行一次迴圈本體',
          'while 可以使用 break，do-while 不行',
          'do-while 只能用於字元處理',
        ],
        answer: 1,
        explanation: '`while` 先檢查條件再執行；`do-while` 先執行一次再檢查條件。即使條件一開始就為假，do-while 的本體也會執行一次。適合需要至少執行一次的場景（如選單）。',
      },
      {
        id: 'c3',
        type: 'multiple',
        difficulty: 'medium',
        question: '`break` 敘述在迴圈中的作用是？',
        code: null,
        options: [
          '暫停執行 0.5 秒',
          '跳過本次迭代，繼續下一次',
          '立即離開最內層的迴圈或 switch',
          '結束整個程式',
        ],
        answer: 2,
        explanation: '`break` 立即終止最內層的迴圈（for/while/do-while）或 switch 敘述。`continue` 才是跳過當前迭代繼續下一次。注意：break 只跳出一層，巢狀迴圈需多個 break。',
      },
      {
        id: 'c4',
        type: 'multiple',
        difficulty: 'medium',
        question: '以下程式碼輸出為何？',
        code: '#include <stdio.h>\nint main() {\n    for (int i = 0; i < 3; i++) {\n        if (i == 1) continue;\n        printf("%d ", i);\n    }\n    return 0;\n}',
        options: ['0 1 2', '0 2', '1', '0 1'],
        answer: 1,
        explanation: '`continue` 跳過 i=1 的那次迭代（不執行 printf），其他迭代正常執行。所以輸出 0（i=0）和 2（i=2），即 "0 2"。',
      },
      {
        id: 'c5',
        type: 'multiple',
        difficulty: 'hard',
        question: 'switch 敘述中，若沒有 `break`，會發生什麼？',
        code: null,
        options: [
          '編譯錯誤',
          '只執行符合 case 的程式碼',
          '從符合的 case 開始，繼續執行後續所有 case（fall-through）',
          '自動跳到 default',
        ],
        answer: 2,
        explanation: '這稱為 "fall-through" 行為：程式在匹配到某個 case 後，若沒有 break，會繼續執行下一個 case 的程式碼，直到遇到 break 或 switch 結束。有時候 fall-through 是故意設計的，但通常需要 break。',
      },
      {
        id: 'c6',
        type: 'fill',
        difficulty: 'easy',
        question: '填入關鍵字：`_____ (score >= 60) { printf("Pass"); }`',
        code: null,
        answer: 'if',
        hint: '條件判斷關鍵字',
        explanation: '`if` 是條件判斷關鍵字。語法：`if (條件) { 程式碼 }`。若條件為真（非零），執行大括號內的程式碼。',
      },
    ],

    functions: [
      {
        id: 'f1',
        type: 'multiple',
        difficulty: 'easy',
        question: '函式宣告（function declaration / prototype）的目的是？',
        code: null,
        options: [
          '直接執行函式',
          '告訴編譯器函式的名稱、回傳型別和參數型別',
          '為函式分配記憶體',
          '定義函式的實作內容',
        ],
        answer: 1,
        explanation: '函式原型（prototype）讓編譯器在函式實際定義之前就知道其簽章，可在文件頂部宣告。格式：`回傳型別 函式名稱(參數型別 參數名稱);`',
      },
      {
        id: 'f2',
        type: 'multiple',
        difficulty: 'medium',
        question: '若函式不需要回傳任何值，回傳型別應設為？',
        code: null,
        options: ['null', 'none', 'void', '0'],
        answer: 2,
        explanation: '`void` 代表「沒有型別」或「沒有值」。宣告回傳型別為 void 的函式不需要 return 敘述（或使用不帶值的 `return;`）。',
      },
      {
        id: 'f3',
        type: 'multiple',
        difficulty: 'medium',
        question: '以下函式的回傳值是什麼？',
        code: 'int add(int a, int b) {\n    return a + b;\n}\n// 呼叫：int result = add(3, 4);',
        options: ['3', '4', '7', '12'],
        answer: 2,
        explanation: '`add(3, 4)` 將 a=3, b=4 代入函式，計算 3 + 4 = 7 並回傳。result 的值為 7。',
      },
      {
        id: 'f4',
        type: 'multiple',
        difficulty: 'hard',
        question: 'C 語言預設的參數傳遞方式是？',
        code: null,
        options: [
          '傳址（pass by reference）',
          '傳值（pass by value）',
          '傳指標（pass by pointer）',
          '依型別自動決定',
        ],
        answer: 1,
        explanation: 'C 語言使用「傳值」（pass by value），函式收到的是參數的副本，修改函式內的參數不會影響原來的變數。若要修改原始變數，需傳遞指標（pass by pointer）。',
      },
      {
        id: 'f5',
        type: 'multiple',
        difficulty: 'hard',
        question: '遞迴函式（recursive function）必須具備什麼？',
        code: null,
        options: [
          '必須使用 while 迴圈',
          '必須有基礎情況（base case）以避免無限遞迴',
          '必須回傳 void',
          '必須在 main() 之前宣告',
        ],
        answer: 1,
        explanation: '遞迴函式呼叫自身，必須有「基礎情況」（base case）來終止遞迴，否則會無限遞迴直到堆疊溢出（stack overflow）。例如階乘：`if (n == 0) return 1;` 就是基礎情況。',
      },
    ],

    arrays: [
      {
        id: 'a1',
        type: 'multiple',
        difficulty: 'easy',
        question: '宣告 `int arr[5];` 後，有效的索引範圍是？',
        code: null,
        options: ['1 到 5', '0 到 5', '0 到 4', '1 到 4'],
        answer: 2,
        explanation: 'C 語言陣列索引從 0 開始。`int arr[5]` 有 5 個元素：arr[0], arr[1], arr[2], arr[3], arr[4]。存取 arr[5] 是越界（out of bounds），屬於未定義行為。',
      },
      {
        id: 'a2',
        type: 'multiple',
        difficulty: 'medium',
        question: '以下初始化後，`arr[2]` 的值是什麼？',
        code: 'int arr[] = {10, 20, 30, 40, 50};',
        options: ['20', '30', '2', '40'],
        answer: 1,
        explanation: '陣列索引從 0 開始：arr[0]=10, arr[1]=20, arr[2]=30, arr[3]=40, arr[4]=50。所以 arr[2] = 30。',
      },
      {
        id: 'a3',
        type: 'multiple',
        difficulty: 'hard',
        question: '將陣列傳入函式時，實際傳遞的是什麼？',
        code: null,
        options: [
          '整個陣列的副本',
          '陣列的大小',
          '指向陣列第一個元素的指標',
          '陣列的最後一個元素',
        ],
        answer: 2,
        explanation: '將陣列傳入函式時，C 語言會將陣列「退化」（decay）為指向第一個元素的指標。因此函式內修改陣列元素會影響原始陣列，且 sizeof() 在函式內無法取得正確陣列大小。',
      },
      {
        id: 'a4',
        type: 'fill',
        difficulty: 'easy',
        question: '宣告一個包含 10 個整數的陣列：`int numbers[_____];`',
        code: null,
        answer: '10',
        hint: '填入陣列元素數量',
        explanation: '方括號內填入陣列大小（元素數量）。`int numbers[10]` 宣告了可儲存 10 個整數的陣列，索引從 0 到 9。',
      },
    ],

    pointers: [
      {
        id: 'p1',
        type: 'multiple',
        difficulty: 'easy',
        question: '指標（pointer）儲存的是什麼？',
        code: null,
        options: ['一個整數值', '一個字元', '記憶體位址', '陣列大小'],
        answer: 2,
        explanation: '指標是一種變數，其儲存的值是另一個變數的記憶體位址。例如 `int *p = &x;` 讓 p 儲存變數 x 的位址，而非 x 的值。',
      },
      {
        id: 'p2',
        type: 'multiple',
        difficulty: 'easy',
        question: '`&` 運算子（取址運算子）的作用是？',
        code: null,
        options: [
          '邏輯 AND 運算',
          '取得變數的記憶體位址',
          '解參考指標',
          '位元 AND 運算（視情況而定）',
        ],
        answer: 1,
        explanation: '在變數前加 `&` 可取得該變數的記憶體位址。例如 `int x = 5; printf("%p", &x);` 會印出 x 的位址。注意：`&` 也是位元 AND，但在宣告/表達式中作為一元運算子時是取址。',
      },
      {
        id: 'p3',
        type: 'multiple',
        difficulty: 'medium',
        question: '`*p` 在指標 p 已初始化後代表什麼？',
        code: null,
        options: [
          'p 的位址',
          '乘法運算',
          '解參考：取得 p 所指向位址的值',
          '宣告新的指標',
        ],
        answer: 2,
        explanation: '`*`（解參考運算子，dereference operator）用於取得指標指向的值。若 `int x = 10; int *p = &x;`，則 `*p` 的值為 10，且 `*p = 20` 會將 x 改為 20。',
      },
      {
        id: 'p4',
        type: 'multiple',
        difficulty: 'hard',
        question: '`NULL` 指標是指什麼？',
        code: null,
        options: [
          '指向值為 0 的整數的指標',
          '不指向任何有效記憶體位置的指標',
          '已被 free() 釋放的指標',
          '指向字串結尾的指標',
        ],
        answer: 1,
        explanation: '`NULL` 是一個特殊的指標值（通常為 0 或 (void*)0），代表指標目前不指向任何有效位址。使用指標前應檢查是否為 NULL，解參考 NULL 指標會導致程式崩潰（segmentation fault）。',
      },
      {
        id: 'p5',
        type: 'fill',
        difficulty: 'medium',
        question: '宣告一個指向整數的指標：`int _____ ptr;`',
        code: null,
        answer: '*',
        hint: '宣告指標需要的符號',
        explanation: '`int *ptr;` 宣告了一個指向整數的指標。`*` 在宣告時表示「這是一個指標」，而非解參考。ptr 存放的是某個 int 變數的記憶體位址。',
      },
    ],

    strings: [
      {
        id: 's1',
        type: 'multiple',
        difficulty: 'easy',
        question: 'C 語言中，字串是以什麼方式儲存的？',
        code: null,
        options: ['string 型別', '字元陣列，以 \\0 結尾', 'char 型別', 'text 型別'],
        answer: 1,
        explanation: 'C 語言沒有內建字串型別。字串以 `char` 陣列表示，最後一個元素為空字元 `\\0`（null terminator），告訴字串函式字串在此結束。',
      },
      {
        id: 's2',
        type: 'multiple',
        difficulty: 'medium',
        question: '`strlen()` 函式的功能是？',
        code: null,
        options: [
          '設定字串長度',
          '回傳字串的字元數（不含 \\0）',
          '比較兩個字串',
          '複製字串',
        ],
        answer: 1,
        explanation: '`strlen()` 計算並回傳字串的長度（不含結尾的 \\0）。例如 `strlen("Hello")` 回傳 5。需包含 `<string.h>` 標頭檔。',
      },
      {
        id: 's3',
        type: 'multiple',
        difficulty: 'medium',
        question: '為何不應該用 `==` 比較兩個字串？',
        code: null,
        options: [
          '`==` 不支援字元比較',
          '`==` 比較的是記憶體位址，而非字串內容',
          '`==` 只能比較數字',
          '字串比較需要 C++ 才能使用 `==`',
        ],
        answer: 1,
        explanation: '字串是 char 陣列，`==` 比較的是陣列的起始位址（指標值），而非內容。應使用 `strcmp(str1, str2)` 來比較字串內容（回傳 0 表示相等）。',
      },
      {
        id: 's4',
        type: 'fill',
        difficulty: 'easy',
        question: '`printf` 中，輸出字串使用的格式符是 _____',
        code: null,
        answer: '%s',
        hint: 's 代表 string',
        explanation: '`%s` 是字串格式符，用於 printf 輸出字串。例如 `printf("%s", name);`。常見格式符：%d（整數）、%f（浮點數）、%c（字元）、%s（字串）。',
      },
    ],

    structs: [
      {
        id: 'st1',
        type: 'multiple',
        difficulty: 'easy',
        question: '結構體（struct）的用途是？',
        code: null,
        options: [
          '定義函式的結構',
          '將不同型別的資料組合成一個自訂型別',
          '建立物件導向的類別',
          '宣告全域變數',
        ],
        answer: 1,
        explanation: '`struct` 允許你將多個不同型別的變數組合成一個新的複合型別。例如將姓名（char）、年齡（int）、成績（float）組成 Student 結構體，讓相關資料聚合在一起。',
      },
      {
        id: 'st2',
        type: 'multiple',
        difficulty: 'medium',
        question: '存取結構體成員使用哪個運算子（變數為結構體實例時）？',
        code: null,
        options: ['->', '::', '.', '@'],
        answer: 2,
        explanation: '結構體實例（非指標）使用 `.`（點運算子）存取成員。例如 `student.name`。若是指標，則使用 `->`：`ptr->name` 等同於 `(*ptr).name`。',
      },
      {
        id: 'st3',
        type: 'multiple',
        difficulty: 'hard',
        question: '`typedef struct` 的優點是？',
        code: null,
        options: [
          '讓結構體支援繼承',
          '宣告時不需要再寫 struct 關鍵字',
          '增加結構體執行速度',
          '允許結構體有函式成員',
        ],
        answer: 1,
        explanation: '`typedef struct { ... } TypeName;` 建立型別別名，之後宣告變數時不需寫 `struct TypeName var`，直接寫 `TypeName var` 即可。讓程式碼更簡潔。',
      },
    ],

    memory: [
      {
        id: 'm1',
        type: 'multiple',
        difficulty: 'easy',
        question: '`malloc()` 函式的作用是？',
        code: null,
        options: [
          '釋放記憶體',
          '在堆積（heap）動態配置指定大小的記憶體',
          '初始化陣列為零',
          '計算記憶體大小',
        ],
        answer: 1,
        explanation: '`malloc(size)` 在執行期（runtime）於堆積（heap）配置 size 個位元組的記憶體，並回傳 void 指標。若配置失敗回傳 NULL。需包含 `<stdlib.h>`，且使用完畢必須 free()。',
      },
      {
        id: 'm2',
        type: 'multiple',
        difficulty: 'medium',
        question: '使用 `malloc()` 配置記憶體後，為何必須呼叫 `free()`？',
        code: null,
        options: [
          '讓程式執行更快',
          '避免記憶體洩漏（memory leak）',
          '必要的語法規定',
          '初始化下一次 malloc 的記憶體',
        ],
        answer: 1,
        explanation: '動態配置的記憶體不會自動釋放。若不 free()，程式結束前這塊記憶體一直被佔用，稱為「記憶體洩漏」（memory leak）。長期運行的程式若有洩漏，可能耗盡系統記憶體。',
      },
      {
        id: 'm3',
        type: 'multiple',
        difficulty: 'hard',
        question: '`calloc()` 和 `malloc()` 的差異是？',
        code: null,
        options: [
          '兩者完全相同',
          'calloc 將配置的記憶體初始化為零，malloc 不會',
          'calloc 只能配置一個元素，malloc 可以配置陣列',
          'calloc 在堆疊，malloc 在堆積',
        ],
        answer: 1,
        explanation: '`calloc(n, size)` 配置 n 個大小為 size 的元素，並將所有位元初始化為 0；`malloc(size)` 只配置記憶體，內容是未定義的垃圾值。`calloc` 更安全但略慢。',
      },
      {
        id: 'm4',
        type: 'fill',
        difficulty: 'medium',
        question: '釋放動態配置記憶體的函式是 _____',
        code: null,
        answer: 'free',
        hint: '配對 malloc 使用',
        explanation: '`free(ptr)` 釋放 ptr 指向的動態配置記憶體。free 後不應再使用該指標（懸空指標 dangling pointer），建議立即設為 NULL：`free(ptr); ptr = NULL;`',
      },
    ],
  },
};
